title: Francisco Navarro
logo: profile-pic round.png
description: <h3 align="left">Connect with me:</h3>
<p align="left">
<a href="https://www.linkedin.com/in/francisco-e-navarro/" target="blank"><img align="center" src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/linked-in-alt.svg" alt="https://www.linkedin.com/in/francisco-e-navarro/" height="30" width="40" /></a>
</p>
show_downloads: false
theme: jekyll-theme-minimal
